// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyANSlumd-_hYffulWovUVl1pU5aGMvcjEU',
    appId: '1:213085468992:web:a2647a4a2d8598895822a5',
    messagingSenderId: '213085468992',
    projectId: 'oneai-b86d4',
    authDomain: 'oneai-b86d4.firebaseapp.com',
    storageBucket: 'oneai-b86d4.firebasestorage.app',
    measurementId: 'G-9XPW7HS25P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC_jvLoxokKnQDmeBLTMJissvrty5iV79c',
    appId: '1:213085468992:android:7cf776f7e58d3a9f5822a5',
    messagingSenderId: '213085468992',
    projectId: 'oneai-b86d4',
    storageBucket: 'oneai-b86d4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAYEiDgp2U_rp5TR1DBEdzcGrfXxC2RYvw',
    appId: '1:213085468992:ios:27ea41c51f0363cb5822a5',
    messagingSenderId: '213085468992',
    projectId: 'oneai-b86d4',
    storageBucket: 'oneai-b86d4.firebasestorage.app',
    iosClientId: '213085468992-ha97hrs7nnca517u2vm3p96n3j7p3j8o.apps.googleusercontent.com',
    iosBundleId: 'com.example.oneAi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAYEiDgp2U_rp5TR1DBEdzcGrfXxC2RYvw',
    appId: '1:213085468992:ios:27ea41c51f0363cb5822a5',
    messagingSenderId: '213085468992',
    projectId: 'oneai-b86d4',
    storageBucket: 'oneai-b86d4.firebasestorage.app',
    iosClientId: '213085468992-ha97hrs7nnca517u2vm3p96n3j7p3j8o.apps.googleusercontent.com',
    iosBundleId: 'com.example.oneAi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyANSlumd-_hYffulWovUVl1pU5aGMvcjEU',
    appId: '1:213085468992:web:227afe62924c7d635822a5',
    messagingSenderId: '213085468992',
    projectId: 'oneai-b86d4',
    authDomain: 'oneai-b86d4.firebaseapp.com',
    storageBucket: 'oneai-b86d4.firebasestorage.app',
    measurementId: 'G-WBBT9TZ30D',
  );
}
